_target_: bo_protein.models.encoder.CNNEncoder
name: cnn
out_dim: 16
batch_size: 256
num_epochs: 128
patience: 32
lr: 1e-3
mask_ratio: 0.125
max_shift: 0
model_kwargs:
  k: 128
  kernel_size: 5
  p: 0.
  layernorm: True