_target_: bo_protein.models.gp_models.SingleTaskVRFFGP
max_shift: 4
mask_size: 0
bootstrap_ratio: null
min_num_train: 128
lr: 1e-2
bs: 32
num_epochs: 50
holdout_ratio: 0.2
early_stopping: True
patience: 128
eval_period: 1
feature_dim: 16
out_dim: ${task.obj_dim}
num_samples: 256
#encoder:
#  _target_: bo_protein.models.nn_models.CNN
#  dict_size: 25
#  k: 64
#  p: 0.
#  out_dim: ${surrogate.feature_dim}
#  layernorm: False
encoder_wd: 1e-4
#<<<<<<< HEAD
# covar_module:
#   _target_: gpytorch.kernels.MaternKernel
#   ard_num_dims: ${surrogate.feature_dim}
#lengthscale_prior:
#  _target_: gpytorch.priors.NormalPrior
#  loc: 0.7
#  scale: 1e-2
#=======
covar_module:
  _target_: gpytorch.kernels.MaternKernel
  ard_num_dims: ${surrogate.feature_dim}
  batch_shape:
    - ${task.obj_dim}
  lengthscale_prior:
   _target_: gpytorch.priors.NormalPrior
   loc: 0.7
   scale: 1e-2
#>>>>>>> gp tweaks
likelihood:
  _target_: gpytorch.likelihoods.GaussianLikelihood
  batch_shape:
    - ${task.obj_dim}
#  noise_constraint:
#    _target_: gpytorch.constraints.GreaterThan
#    lower_bound: 1e-4